### ISSUE TITLE
several wrong error messages

### ISSUE THREAD

**Issue by Bananeweizen** [enofex/taikai#57]
Just reading through the sources, I believe that several of the "should match" rules have a wrong error message (wrongly saying "should NOT"). Example https://github.com/enofex/taikai/blob/d9c1d2e78669f6382ba4fd91e87b107e389783cc/src/main/java/com/enofex/taikai/java/NamingConfigurer.java#L47 (and several more in the same class).

**Comment by mnhock** [comment]
Thanks for finding!
