### ISSUE TITLE
Add Spring properties customizer

### ISSUE THREAD

**Issue by piotrooo** [enofex/taikai#63]
Thanks for this super helpful library :pray: 

While using this library, I think (this is one of my cases) it would be great to add a customizer for the Spring properties. The API could look like this (should be discussed):

```
builder()
    .spring(spring -> spring
        .properties(properties -> properties
            .hasConfigurationPropertiesAnnotation()
            .hasValidatedAnnotation()
            .namesShouldEndWithProperties()
        )
    )
```

**Comment by mnhock** [comment]
Thanks @piotrooo! Great ideas, will be part of the next release. Will adjust some naming in order to be consistent with the other rules.
