### ISSUE TITLE
Bug in the `shouldBeAnnotatedWithValidated` method

### ISSUE THREAD

**Issue by piotrooo** [enofex/taikai#68]
There is a bug in the description of the `PropertiesConfigurer.shouldBeAnnotatedWithValidated` method:

```
"Configuration properties annotated with %s should be annotated with %s as well"
```

This string specifies two placeholders to be replaced, only one is passed to the `formatted` method.

The following exception is thrown:

```
java.util.MissingFormatArgumentException: Format specifier '%s'
```

**Comment by mnhock** [comment]
Thanks! This already fixed and part of the release today.
