### ISSUE TITLE
Block imports in Test classes

### ISSUE THREAD

**Issue by erikpragt-connectid** [enofex/taikai#82]
Hi, apologies for another question. I have a lot of JUnit 5 tests written in Kotlin, and some of these tests are using Hamcrest, some are using `kotlin.test`, and some of them AssertJ. I'd like to block the use of Hamcrest and Kotlin test, but I don't see how I can do this.

I've attempted to add it here:

```
                .java(java -> java
                        .imports(imports -> imports
                                .shouldNotImport("org.hamcrest"))
```

But that didn't do anything. I also tried it on the test block:

```
                .test(test -> test
                        .junit5(junit5 -> junit5
                                .classesShouldNotBeAnnotatedWithDisabled()
                                .methodsShouldNotBeAnnotatedWithDisabled()
                        ))
```

But I couldn't find a `shouldNotImport` method on either the test or junit method. 

Any way to address this?

**Comment by mnhock** [comment]
There is a shouldNotImport (https://github.com/enofex/taikai/blob/main/docs/USERGUIDE.md#java-rules), but as the doc describe it goes for main classes not test classes. 

But you can provide a custom configuratzion like: https://github.com/enofex/taikai/blob/main/docs/USERGUIDE.md#9-customization.

The regex would be like in the doc:   .shouldNotImport("..shaded..")

**Comment by erikpragt-connectid** [comment]
Thanks, that looks interesting. However, I'm not sure if the code example isn't correct or the code isn't, but the linked code example doesn't work:

```
ImportsConfigurer configurer = new ImportsConfigurer();
configurer.shouldNotImport("com.example.package", Configuration.of("com.example.namespace", Namespace.IMPORT.WITHOUT_TESTS));
```

The problem is that the constructor of the ImportsConfigurer is package protected, so I can't instantiate it as per the example. 

Also, bit of a sidenote, but have you seen https://docs.konsist.lemonappdev.com/ by any chance?

**Comment by mnhock** [comment]
Thanks pointing it out, fixed the incorrect doc with https://github.com/enofex/taikai/commit/c3d3728fa7a7c797765e4963598f386cc8315d34.

Thanks for the information about this library!

**Comment by erikpragt-connectid** [comment]
Hi @mnhock , thanks for updating the documentation. There's a small typo in the updated documentation though, I left a comment on the PR.
